replicaCount: 1
environment: development
image:
  pullPolicy: Always
  name: docker.io/sundargsvstar-wars-service
  tag: latest

imagePullSecrets:
  name: registry-json-key

# Define service
service:
  name: star-wars-service
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080
# Define resources
resources: {}
  # limits:
  #   memory: 1024Mi
  # requests:
  #   memory: 64Mi

## Liveness & Readiness Probes
livenessProbe: {}
#  httpGet:
#    path: /
#    port: 8080
#  initialDelaySeconds: 30
#  timeoutSeconds: 5
#  periodSeconds: 3
readinessProbe: {}
#  httpGet:
#    path: /
#    port: 8080
#  initialDelaySeconds: 30
#  timeoutSeconds: 5
#  periodSeconds: 3
restartPolicy: Always

## Setup Ingress
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
  tls:
    enabled: true
    secretName: star-wars-tls
    domain: "*.starwars.com"
  domain: api.starwars.com
  paths:
    path: /dev

horizontalautoscaling:
  enabled: false
  cpuUtilizationPercentage: 80
  memoryUtilization: 512Mi

nameOverride:
fullnameOverride:
nodeSelector: {}
tolerations: []
affinity: {}
